INSERT INTO SABOR (IDSABOR, NOMBRE) VALUES (1, 'Vainilla');
INSERT INTO SABOR (IDSABOR, NOMBRE) VALUES (2, 'Nata');
INSERT INTO SABOR (IDSABOR, NOMBRE) VALUES (3, 'Fresa');

INSERT INTO TIPOHELADO (IDTIPOHELADO, NOMBRE, IDSABOR) VALUES (1, 'Paleta Agua', 1);
INSERT INTO TIPOHELADO (IDTIPOHELADO, NOMBRE, IDSABOR) VALUES (2, 'Turron', 1);
INSERT INTO TIPOHELADO (IDTIPOHELADO, NOMBRE, IDSABOR) VALUES (3, 'Galleta', 3);
INSERT INTO TIPOHELADO (IDTIPOHELADO, NOMBRE, IDSABOR) VALUES (4, 'Sundae', 3);
INSERT INTO TIPOHELADO (IDTIPOHELADO, NOMBRE, IDSABOR) VALUES (5, 'Vasito (Helado Cremoso)', 2);
INSERT INTO TIPOHELADO (IDTIPOHELADO, NOMBRE, IDSABOR) VALUES (6, 'Batido', 2);