INSERT INTO SABOR (IDSABOR, NOMBRE) VALUES (1, 'Vainilla');
INSERT INTO SABOR (IDSABOR, NOMBRE) VALUES (2, 'Nata');
INSERT INTO SABOR (IDSABOR, NOMBRE) VALUES (3, 'Fresa');

INSERT INTO TIPOHELADO (IDTIPOHELADO, NOMBRE, IDSABOR) VALUES (1, 'Vasitos', 1);
INSERT INTO TIPOHELADO (IDTIPOHELADO, NOMBRE, IDSABOR) VALUES (2, 'Batidos', 2);
INSERT INTO TIPOHELADO (IDTIPOHELADO, NOMBRE, IDSABOR) VALUES (3, 'Turrones', 3);